//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadohinConrol18.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZadohinAccountingStudentEntities : DbContext
    {
        public ZadohinAccountingStudentEntities()
            : base("name=ZadohinAccountingStudentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountingCollege> AccountingCollege { get; set; }
        public DbSet<ActivityStudent> ActivityStudent { get; set; }
        public DbSet<Directions> Directions { get; set; }
        public DbSet<GroupStudent> GroupStudent { get; set; }
        public DbSet<Specialization> Specialization { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<AccountingView> AccountingView { get; set; }
        public DbSet<View_2> View_2 { get; set; }
    }
}
