//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadohinConrol18.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingView
    {
        public string Группа { get; set; }
        public Nullable<int> Балл { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public int id { get; set; }
    }
}
