//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadohinConrol18.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directions
    {
        public Directions()
        {
            this.ActivityStudent = new HashSet<ActivityStudent>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ActivityStudent> ActivityStudent { get; set; }
    }
}
